### ISSUE TITLE
STIG Rule/Group ID Format Update (DFR Report)

### ISSUE THREAD

**Issue by TheCleverEpithet** [squinky86/STIGQter#67] opened 2020-04-03 20:23 UTC
See issue #66 

This same issue with the STIG rule / SV number appears to effect the "Findings" (Column H) and "CCIs" (Column D) worksheets in the "Detailed Findings Report" report as well.

**Comment by squinky86** [comment] 2020-05-04 20:42
Closing as duplicate of #69.

**Closed by squinky86** 2020-05-04 20:42 UTC
Labels: bug
