### ISSUE TITLE
MS SQL 2012 Instance

### ISSUE THREAD

**Issue by 4merFatMan** [squinky86/STIGQter#60] opened 2020-02-14 22:50 UTC
STIGQter will not import MS SQL 2012 Instance files.  Causes STIGQter to crash.

**Comment by squinky86** [comment] 2020-02-18 20:59
Download the latest STIG from https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_MS_SQL_Server_2012_V1R20_STIG.zip (There was briefly a "Database" STIG and an "Installation" STIG. It has now been replaced with the corrected "Database" and "Instance" STIGs.) If you created checklists with the old Installation STIG, it might cause some issues. If you used R19, R17, or earlier, you may be running into Issue #40.

Download the newer V1R20 and try it. If you're still having trouble, send me a .stigqter file to debug.

**Comment by squinky86** [comment] 2020-02-24 13:40
I am betting the crash was caused by #61 and that the import error was caused because of the fast rename between "Installation" and "Instance." Closing for now; feel free to reopen or contact me directly with a use case.

**Closed by squinky86** 2020-02-24 13:40 UTC
Labels: bug
